include: /risk1/chengxilong/dog_breed_identificatiopn/cfg/model/base.yaml

model: resnext101_32x8dpretrain

optim: Adam
optim_args:
  lr: 0.0001
lr_sched: StepLR
lr_sched_args:
  gamma: 0.5
  step_size: 50